### ISSUE TITLE
GitHub contribution badge

### ISSUE THREAD

**Issue by Vanshiii203** [MrKrishnaAgarwal/Swags-for-Developers#23]
I would like to add the GitHub contribution badges to display the contributors of repository in README file. 
![Screenshot_20221004-075606~2](https://user-images.githubusercontent.com/94471189/193721348-3da9d6bc-bdc8-47cf-88bf-049b4dd2a72b.jpg)

**Comment by MrKrishnaAgarwal** [comment]
I have already set up that, It will be updated soon.

Thanks
Please open a issue with a relevant fix or addition next time.
