### ISSUE TITLE
Adding Kong website to swags.md

### ISSUE THREAD

**Issue by Vanshiii203** [MrKrishnaAgarwal/Swags-for-Developers#24]
I want to add _KONG_ to swags.md file 
![Screenshot_20221004-080004~2](https://user-images.githubusercontent.com/94471189/193722002-e97a9473-66a1-425f-9f61-4ddeef8955b4.jpg)
https://konghq.com/

**Comment by MrKrishnaAgarwal** [comment]
Okay, you can add that 🙂
