### ISSUE TITLE
"Contrbuting guide" link in the README doc is broken

### ISSUE THREAD

**Issue by aniketghosh01** [MrKrishnaAgarwal/Swags-for-Developers#3]
[Contrbuting guide](https://github.com/MrKrishnaAgarwal/Swags-for-Developers/blob/main/CONTRIBUTING.md)

**Comment by MrKrishnaAgarwal** [comment]
Please fix it by making a PR
Thanks

**Comment by MrKrishnaAgarwal** [comment]
You can make the PR in Hacktoberfest Contribution Period

**Comment by aniketghosh01** [comment]
> You can make the PR in Hacktoberfest Contribution Period

thank you

**Comment by aniketghosh01** [comment]
@MrKrishnaAgarwal  I was assigned to this issue and was given the permission to contribute during Hacktoberfest period. Why did you then merge another PR?
