### ISSUE TITLE
contributors image in readme file

### ISSUE THREAD

**Issue by Ankurrawat-12** [MrKrishnaAgarwal/Swags-for-Developers#36]
![image](https://user-images.githubusercontent.com/78417225/194754392-c673db37-a187-4acb-93d6-9b95755e8602.png)
like this

**Comment by Ankurrawat-12** [comment]
@MrKrishnaAgarwal  can i have this issue

**Comment by MrKrishnaAgarwal** [comment]
Comment once again

**Comment by MrKrishnaAgarwal** [comment]
Sure @Beast71421

**Comment by Beast61224** [comment]
hey @MrKrishnaAgarwal I think you block my other id 
![image](https://user-images.githubusercontent.com/95344102/194754848-a0ddbea4-bf46-4900-9f91-e11eafa6aca6.png)

I can't fork the repo
![image](https://user-images.githubusercontent.com/95344102/194754892-97a759b8-ba73-4580-93c9-a78d8c9772db.png)

neither can I write in the issue

Please do something

**Comment by MrKrishnaAgarwal** [comment]
> hey @MrKrishnaAgarwal I think you block my other id 
> ![image](https://user-images.githubusercontent.com/95344102/194754848-a0ddbea4-bf46-4900-9f91-e11eafa6aca6.png)
> 
> I can't fork the repo
> ![image](https://user-images.githubusercontent.com/95344102/194754892-97a759b8-ba73-4580-93c9-a78d8c9772db.png)
> 
> neither can I write in the issue
> 
> Please do something

I didn't do anything brother

**Comment by MrKrishnaAgarwal** [comment]
Try again, maybe some issue from your side ig

**Comment by MrKrishnaAgarwal** [comment]
Try again, maybe some issue from your side ig

**Comment by MrKrishnaAgarwal** [comment]
@Beast71421 is it resolved?

**Comment by MrKrishnaAgarwal** [comment]
@Beast61224

**Comment by Ankurrawat-12** [comment]
yes

**Comment by Ankurrawat-12** [comment]
Done @MrKrishnaAgarwal  can you check the pr

**Comment by Ankurrawat-12** [comment]
is this repo EXCLUDED from hacktoberfest
![image](https://user-images.githubusercontent.com/78417225/194755792-179465e4-27bf-4941-8539-195f1cca9eae.png)

**Comment by MrKrishnaAgarwal** [comment]
> is this repo EXCLUDED from hacktoberfest
> ![image](https://user-images.githubusercontent.com/78417225/194755792-179465e4-27bf-4941-8539-195f1cca9eae.png)
> 

Stop commenting, alt account and you have been blocked now.

**Comment by MrKrishnaAgarwal** [comment]
All your alts are blocked, you are spam 🚧
