### ISSUE TITLE
Add leetcode swag

### ISSUE THREAD

**Issue by AnshuPathak-88825** [MrKrishnaAgarwal/Swags-for-Developers#37]

**Comment by AnshuPathak-88825** [comment]
Hey @MrKrishnaAgarwal pls assign me this issue

**Comment by MrKrishnaAgarwal** [comment]
Yes sure 👨‍💻

**Comment by MrKrishnaAgarwal** [comment]
**You have 3 alt accounts, I just carefully.**

Sorry but you are blocked from interacting on my repository now, you are fake 🚧

**Comment by MrKrishnaAgarwal** [comment]
Your alt accounts are: @Beast71421 and one more beast account.

Spam users 🚧
