### ISSUE TITLE
This Hacktoberfest 2023: Add more swag websites

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [MrKrishnaAgarwal/Swags-for-Developers#47]
Hello everyone, you all are free to make a pull request to this repo and add swag earning websites.

Comment below and start working from 1st Oct 2023

**Comment by Anshul1811** [comment]
Hi @MrKrishnaAgarwal 
I am new to Hacktoberfest and open source 
Can you please tell what I am supposed to do in order to contribute to this project?

**Comment by MrKrishnaAgarwal** [comment]
> Hi @MrKrishnaAgarwal 
> 
> I am new to Hacktoberfest and open source 
> 
> Can you please tell what I am supposed to do in order to contribute to this project?
> 
> 

Alright, see basically you'll have to contribute if you know about any swags or goodies earning programs in which we'll have to do a task and in return if we won or complete it we'll get swags.
So basically if you know about any other programs except the ones already listed in the repo, you can make a PR.
