### ISSUE TITLE
ADDITION REQUEST :SWOC EVENT

### ISSUE THREAD

**Issue by Parth4git** [MrKrishnaAgarwal/Swags-for-Developers#56]
Social Winter of Code is an open-source program envisioned by the Social. It aims to bring students into the world of open source development and see the power of unified problem-solving in real time. Event is organized each year in month on jan-feb

SWOC, GitHub swag kits for Top 10 Contributors 
Swags from coding ninja for Top 1

**Comment by Parth4git** [comment]
pls assign to me .I want to work on it

**Comment by MrKrishnaAgarwal** [comment]
Sure @Parth4git

**Comment by MrKrishnaAgarwal** [comment]
@Parth4git I have reopened the issue, please work on it and create a PR. You can refer to [CONTRIBUTING.md](https://github.com/MrKrishnaAgarwal/Swags-for-Developers/blob/main/CONTRIBUTING.md).

**Comment by MrKrishnaAgarwal** [comment]
Not being worked upon, long inactivity.
